name: E2E Tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavour: [alpine, debian, ubi]
    name: e2e (${{ matrix.flavour }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker with buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker

      - name: Run e2e tests
        run: ./e2e/run-tests.sh
        env:
          CONTAINERFILE: Containerfile.${{ matrix.flavour }}
